name: CI
on: [push]
jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Test
        run: npm test -- --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build
